# Generated by Django 5.2.4 on 2025-07-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0002_rename_member_membro'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
