# Generated by Django 4.2.23 on 2025-07-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0003_membro_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField()),
                ('veiculo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto')], max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('distancia', models.FloatField(blank=True, null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.membro')),
            ],
        ),
    ]
