# Generated by Django 4.2.23 on 2025-07-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0004_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='horario',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], default='tarde', max_length=10),
            preserve_default=False,
        ),
    ]
